// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class Assets {
  const Assets._();
  static const String assets_avatar_jpg = 'assets/avatar.jpg';

  static const String assets_images_1cdd829184ea70d3151051b7a04ec794_gif =
      'assets/images/1CDD829184EA70D3151051B7A04EC794.gif';

  static const String assets_images_20180717125724_3342_jpg =
      'assets/images/20180717125724_3342.jpg';

  static const String assets_images_4bfb73f6f47754a842565f3312619e7d_jpg =
      'assets/images/4BFB73F6F47754A842565F3312619E7D.jpg';

  static const String assets_images_56b4f4f3886539dae8d2f3c323b69257_png =
      'assets/images/56B4F4F3886539DAE8D2F3C323B69257.png';
}
